config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resource :geo_selector, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :departments
  has_many :employees
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :company
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :dept_name, :emp_number, :emp_details, :address)
    end
end

app/controllers/geo_selectors_controller.rb
# frozen_string_literal: true

class GeoSelectorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
# frozen_string_literal: true

module DemosHelper
  def demos
    %w[
      book_search
      chat
      calendar
      geo_selector
      gravatar
      reverse_text
      tabular
      time_series
      todo
      validation
    ]
  end

  def render_demo(demo)
    render("/demos/demo") { render demo }
  end

  def render_explanation(&block)
    render "/demos/explanation", &block
  end

  def render_gists(*filepaths)
    render "/demos/gists", filepaths: filepaths, grouped_filepaths: filepaths.group_by { |filepath| language filepath }
  end

  def file_timestamps(filepaths = [])
    filepaths.map { |p| File.mtime(p).iso8601 }
  end

  def file_lines(filepath)
    lines = File.open(Rails.root.join(filepath)).readlines
    lines.reject! { |line| line.to_s.strip =~ /\A(#|\/|\*|<--)/ }
    lines.shift while lines.first.blank?
    lines.pop while lines.last.blank?
    lines
  end

  def language(filepath)
    case File.extname(filepath)
    when ".scss" then "scss"
    when ".html" then "html"
    when ".erb" then "erb"
    when ".js" then "javascript"
    when ".rb" then "ruby"
    end
  end

  def language_title(language)
    case language
    when "scss" then "CSS"
    when "html" then "HTML"
    when "erb" then "ERB"
    when "javascript" then "JavaScript"
    when "ruby" then "Ruby"
    end
  end

  def companies
    companies = Company.all
    companies.pluck(:name,:id)
    #countries.map(&:region).uniq.sort.select(&:present?)
  end

  def departments(company)
    departments = Company.find(company).departments
    departments.pluck(:name,:id)
  end

  def employees(company, department)
    employees = Department.find(department).employees
    employees.pluck(:name,:id)
  end
  
  def emp_details(employee)
    employee = Employee.find(employee)
  end

  def active_chat?(color)
    session[:chat_color] == color.to_s
  end

  def chat_css(color)
    case color.to_sym
    when :red then "bg-danger-light border-danger-light text-danger"
    when :yellow then "bg-warning-light border-warning-light text-warning-dark"
    when :blue then "bg-primary-light border-primary-light text-primary"
    end
  end

  def chat_border_css(color)
    case color.to_sym
    when :red then "border-danger-light"
    when :yellow then "border-warning-light"
    when :blue then "border-primary-light"
    end
  end

  def chat_author?(chat)
    chat[:author] == request.remote_ip
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/demos/_demo.html.erb
<div class="card bg-light border-primary mt-2 shadow rounded-0">
  <div class="card-header border-primary border-bottom bg-primary-lighter bg-demo-header rounded-0">
    <div class="row">
      <div class="col-8">
        <h3 class="card-title"><%= content_for :demo_title %></h3>
        <%= content_for :demo_summary %>
      </div>
    </div>
  </div>
  <div class="card-body p-4"><%= yield %></div>
</div>

app/views/demos/_explanation.html.erb
<h4 class="mt-5 mb-3">
  <i class="fa-fw fas fa-info text-primary opacity-60"></i>
  Explanation
</h4>
<%= yield %>

app/views/demos/index.html.erb
<h1>
  <%= image_tag "stimulus-reflex-logo.svg", style: "height:60px" %>
  Stimulus<strong>Reflex</strong>
  <span class="text-muted">Expo</span>
</h1>

<p class="lead">
StimulusReflex is an exciting new way to build reactive, modern real-time apps. It eliminates the hassle of maintaining state on the client. It's a new way of thinking... and it works with technologies that Rails developers already use, like server rendered HTML, Russian Doll caching, Stimulus and Turbolinks.
</p>

<p>
The demos on this site are an attempt to teach others how to build reactive applications with StimulusReflex.
</p>

app/views/demos/show.html.erb
<%= render "/demos/showcase/#{params[:id]}/show" %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , data: { reflex: "change->GeoSelectorReflex#form" }%>
  </div>

  <div class="field">
    <%= form.label :dept_name %>
    <%= form.text_field :dept_name , data: { reflex: "change->GeoSelectorReflex#form" }%>
  </div>

  <div class="field">
    <%= form.label :emp_number %>
    <%= form.number_field :emp_number , data: { reflex: "change->GeoSelectorReflex#form" }%>
  </div>

  <div class="field">
    <%= form.label :emp_details %>
    <%= form.text_area :emp_details , data: { reflex: "change->GeoSelectorReflex#form" }%>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address , data: { reflex: "change->GeoSelectorReflex#form" }%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dept name</th>
      <th>Emp number</th>
      <th>Emp details</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.dept_name %></td>
        <td><%= employee.emp_number %></td>
        <td><%= employee.emp_details %></td>
        <td><%= employee.address %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Dept name:</strong>
  <%= @employee.dept_name %>
</p>

<p>
  <strong>Emp number:</strong>
  <%= @employee.emp_number %>
</p>

<p>
  <strong>Emp details:</strong>
  <%= @employee.emp_details %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/geo_selectors/_demo.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6">
      <form data-controller="geo-selector" class="m-4" style="max-width:600px">
        <div class="form-group">
          <%= select_tag :company,
            options_for_select(companies.prepend("Select a company..."),@company),
            placeholder: "Select a company...",
            class: "form-control form-control-lg",
            data: { reflex: "change->GeoSelectorReflex#select_company" } %>
        </div>

        <% if @company %>
        <div class="form-group">
          <%= select_tag :department,
            options_for_select(departments(@company).prepend("Select a department..."), @department),
            placeholder: "Select a department...",
            class: "form-control form-control-lg",
            data: { reflex: "change->GeoSelectorReflex#select_department" } %>
        </div>

        <% if @department %>
          <div class="form-group">
            <%= select_tag :employee,
              options_for_select(employees(@company, @department).prepend("Select a employee..."), @employee),
              placeholder: "Select a employee...",
              class: "form-control form-control-lg",
              data: { reflex: "change->GeoSelectorReflex#select_employee" } %>
          </div>
        <% end %>
      </form>
    </div>

    <div class="col-lg-6">
      <% if @employee %>
        <div class="card" style="width: 18rem;">
          <%  employee = emp_details(@employee) %>
            <div class="card-header font-weight-bold">
            <%= employee.name.titleize %> Details
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-lg-left font-weight-bold"> <%= employee.name.capitalize %></li>
              <li class="list-group-item text-lg-left"  > <%= employee.dept_name%></li>
              <li class="list-group-item text-lg-left"><%= employee.emp_number %></li>
              <li class="list-group-item text-lg-left"><%= employee.emp_details %></li>
              <li class="list-group-item text-lg-left"><%= employee.address %></li>
            </ul>
          
        </div>
        <% if @employee == @edit_id %>
        <li class="editing">
          <input type="text" class="edit" value="<%= employee.name %>"
            data-action="keyup->geo_selectors#cancelEdit blur->geo_selectors#cancelEdit"
            data-reflex="change->GeoSelectorReflex#update" data-id="<%= employee.id %>">
        </li>
     
        <% end %>
      <% end %>
      <% end %>
    </div>

         
  </div>
</div>

app/views/geo_selectors/show.html.erb
<%= content_for :demo_title, "Geo Selector" %>
<%= content_for :demo_summary, "Refines GEO options based on user selections" %>
<%= render "/geo_selectors/demo" %>

<%= render_gists(
  "app/views/geo_selectors/_demo.html.erb",
  "app/javascript/controllers/geo_selector_controller.js",
  "app/reflexes/geo_selector_reflex.rb"
) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusReflexDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <%= link_to 'Stimulus Reflex Demo', geo_selector_path ,class: "a1 navbar-brand" %>

  <div class="collapse navbar-collapse" >
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
      <%= link_to 'Add new employee', new_employee_path ,class: "a1 nav-link" %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>